# Generated by Django 4.0.3 on 2022-04-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HighPriority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sector', models.CharField(max_length=120, verbose_name='sectior')),
                ('NoOfScheme', models.CharField(max_length=120, verbose_name='No Of Scheme')),
                ('NoOfUnit', models.CharField(max_length=120, verbose_name='No Of Unit')),
                ('No Of Beneficiary', models.CharField(max_length=120)),
                ('Sanction Amount', models.CharField(max_length=120)),
                ('Release Amount', models.CharField(max_length=120)),
                ('SpentAmount', models.CharField(max_length=120, verbose_name='Spent Amount')),
                ('YetToStart', models.CharField(max_length=120, verbose_name='Yet To Start')),
                ('Ongoing', models.CharField(max_length=120, verbose_name='On Going')),
                ('Completed', models.CharField(max_length=120, verbose_name='completed')),
                ('Scraped', models.CharField(max_length=120, verbose_name='Scraped')),
                ('Remarks', models.CharField(max_length=120, verbose_name='Remarks')),
            ],
        ),
    ]
