# Generated by Django 4.0.3 on 2022-04-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_no of beneficiary_lowpriority_noofbeneficiary_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='highpriority',
            old_name='No Of Beneficiary',
            new_name='NoOfBeneficiary',
        ),
        migrations.RenameField(
            model_name='highpriority',
            old_name='Release Amount',
            new_name='ReleaseAmount',
        ),
        migrations.RenameField(
            model_name='highpriority',
            old_name='Sanction Amount',
            new_name='SanctionAmount',
        ),
        migrations.AlterField(
            model_name='highpriority',
            name='Sector',
            field=models.CharField(max_length=120, verbose_name='Sector'),
        ),
        migrations.AlterField(
            model_name='highpriority',
            name='SpentAmount',
            field=models.CharField(max_length=120, verbose_name='SpentAmount'),
        ),
    ]
